### PR TITLE
chore: update all deps

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: Update all deps

**Why**: Just to get things up-to-date.

**How**:

1. `npx ncu --dep prod,dev --upgrade`
2. npm run validate
3. Fix some linting things
4. `npm run validate`

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs) N/A
- [ ] Tests N/A
- [ ] Typescript definitions updated N/A
- [x] Ready to be merged
      

Any maintainer is welcome to merge this 👍

### CODE REVIEW

**Review by marcosvega91 — APPROVED** [review]
LGTM :)

**Comment by kentcdodds** [comment]
Standby... I'm making one more update.

**Comment by kentcdodds** [comment]
This is ready to go. Anyone can feel free to click the green button if you're happy with the changes :)

**Review by marcosvega91 — APPROVED** [review]

**Comment by marcosvega91** [comment]
I can’t merge here. I don’t have permission 🤷

**Comment by kentcdodds** [comment]
Fixed up! Try again.

**Comment by marcosvega91** [comment]
Thank you :) merged 💪

**Comment by marcosvega91** [comment]
It seams that the CI is failing because of this https://github.com/npm/cli/issues/2033.

I think that we need to update the workflow. We can set the env variable ?

**Comment by kentcdodds** [comment]
I think a better solution is to disable husky in CI (`HUSKY_SKIP_INSTALL=true`) as it doesn't really need to be installed anyway. I just updated my generator: https://github.com/kentcdodds/generator-kcd-oss/commit/d65eb3b40a156eecbe6234b423bb320fb7468e99 (and whoops, it's needed in two places in the `validate.yml`: https://github.com/kentcdodds/generator-kcd-oss/commit/04b37a68262bc248ef7dc93ceade392bba116741).

**Pull request merged**
