### PR TITLE
fix(type): ignore maxlength based on input type

### LINKED ISSUE #418: userEvent.type honors maxLength when it's not supposed to
- `@testing-library/user-event` version:
- Testing Framework and version:
  
- DOM Environment:
  

Relevant code or config

Dependencies
```
@testing-library/dom 7.21.5
@testing-library/react 10.4.4
@testing-library/user-event 12.0.11
react 16.12.0
react-dom 16.12.0
react-scripts 3.4.1
```

Failing test case
```javascript
it("should not honor maxLength on input type='number'", () => {
    const changeHandler = jest.fn();
    const { getByDisplayValue } = render(
      <input maxLength="3" type="number" value="123" onChange={changeHandler} />
    );
    const input = getByDisplayValue("123");
    userEvent.type(input, "456");
    expect(changeHandler).toHaveBeenCalledTimes(3);
  });
```

What you did:
Use userEvent.type on input with type=number and maxLength

What happened:
Fail the test case above

```
expect(jest.fn()).toHaveBeenCalledTimes(3)

Expected mock function to have been called three times, but it was called zero times.

  20 |     );
  21 |     const input = getByDisplayValue("123");
  22 |     userEvent.type(input, "456");
> 23 |     expect(changeHandler).toHaveBeenCalledTimes(3);
  24 |   });
  25 | });
```

Reproduction repository:
https://codesandbox.io/s/stupefied-booth-9ov2i?file=/src/input.test.js:522-888

Problem description:
I am trying to test my custom function to prevent user types more than `maxLength` but I can't test it because `userEvent.type()` honor the `maxLength` on `type='number'` (potentially other type as well) even though that's not the case in practice (check out codesandbox `src/index.js`).

`userEvent.type()` gives me false positive in passing my test case

Suggested solution:
Add condition such as:
```javascript
const honorMaxLengthType = new Set(['text']);
const elemType = element.getAttribute('type');
if (maxLength < 0 || !honorMaxLengthType.has(elemType) ) {
  ...
} else {
  ...
}
```
https://github.com/testing-library/user-event/blob/448046c237482837d18439ed9fc1128065e641f3/src/utils.js#L129

### PR DESCRIPTION
**Pull request by maxnewlands**
**What**:

Ignore the `maxlength` attribute on `input` elements if the provided `type` is not meant to support it.

**Why**:

Closes #418 

**How**:

Before calculating the new value for the control, confirm that the element is an `input` whose type is one that supports the maxlength attribute, or that the element is a `textarea`. Add a test for the `textarea` case and `input[type=number]`, addressing the original bug report.

**Checklist**:

- [ ] ~Documentation~ N/A? (Happy to update any relevant docs!)
- [x] Tests
- [ ] ~Typings~ N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by maxnewlands** [comment]
Thanks for the review, @marcosvega91 ! I'm new here; can I do anything to help get this merged?

**Comment by kentcdodds** [comment]
@all-contributors please add @maxnewlands for code and tests

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by maxnewlands** [comment]
@kentcdodds Sounds good, thanks!

**Pull request merged**
