### PR TITLE
feat(specialChars): Create and expose `specialChars` map

### PR DESCRIPTION
**Pull request by vasilii-kovalev**
**What**: Create and expose `specialChars` map

**Why**:
* It can help to avoid typos providing the constant values;
* Instead of creating the set manually in each project again and again, it could be more convenient to use the official, always up-to-date one.

**How**:
* Create a constant `specialCharMap`
* Link it with `specialCharCallbackMap`
* Export the constant from `src/type.js` and create a named export of the constant called `specialChars` in `src/index.js`
* Add an appropriate enum in `typings/index.d.ts` called `specialChars`
* Add `specialChars` section to `README.md`

**Checklist**:

- [X] Documentation
- [ ] Tests
- [X] Typings
- [X] Ready to be merged
      

P.S.: I've defined enum because `const` is not allowed in `index.d.ts`. If `src/type.js` could be written in TypeScript, it could be possible to use a [const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) syntax instead, so the `specialCharMap` constant could be a single source of truth.

### CODE REVIEW

**Comment by vasilii-kovalev** [comment]
Also `type` and `specialChars` sections should be in sync, but I can't figure out, how to conveniently combine them.

**Review by marcosvega91 — APPROVED** [review]
For me seams cool, thanks @vasilii-kovalev  😄  👍

**Review by marcosvega91 — APPROVED** [review]
For me is still ok, let's wait the opinion of someone else, thank you for your works 😄

**Comment by vasilii-kovalev** [comment]
@kentcdodds, hello!
Could you take a look at this PR, please?

**Review by kentcdodds — APPROVED** [review]
I guess I'm ok with this. I personally wouldn't use it, but I can understand why others might 👍

**Comment by kentcdodds** [comment]
I'm good with this, but I'm going to let someone else merge it :)

**Comment by kentcdodds** [comment]
@all-contributors please add @vasilii-kovalev for code and docs

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Pull request merged**
