### PR TITLE
fix(tab): skip elements with `visibility:hidden`

### PR DESCRIPTION
**Pull request by Dennis273**
**What**:

Calling `userEvent.tab` focuses on element with `visibility: hidden`, which is not expected.

**Why**:
It breaks use cases related to `visibility:hidden` and `userEvent.tab`

**How**:

It is fixed by checking whether the target element has style `visibility: hidden`.

**Checklist**:

- [N/A] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by ph-fritsche** [comment]
Thanks a lot for your contribution :heart: 

I'm not sure yet if it's worth the merge conflict with [v14.0.0-beta](https://github.com/testing-library/user-event/tree/v14.0.0-beta). We'll drop support for `v13` as soon as `v14` is considered stable.
What do you think about targeting `beta` with this change?

**Comment by Dennis273** [comment]
@ph-fritsche 

It'll be nice if this issue can be fixed on `v13` since we'll still be using `v13` for a while before we can migrate to `v14`

I can make another PR to `beta`  fixing this issue later this week.

**Comment by ph-fritsche** [comment]
I've merged the other PR. Would you share why you expect the migration to be put on hold for a while?
We merged the remaining PRs on `main` before starting `alpha` and pushed through all breaking changes so that if the need for a fix or feature arises, anyone with that need could switch to the new version.
This change is small and the fixed code exists similarly in both branches so it might be reasonable to merge this in both. But I'm a little hesitant to even start gauging upcoming changes in that regard.

**Comment by Dennis273** [comment]
🤔    We have to make tests using `userEvent` from syncronous to asyncronous to use `v14`. I was not sure whether it is worthless making those changes. But the discussion in #504 make great sense so I'm willing to do the migration as soon as `v14` is released.

I'll close this PR.

**Pull request closed without merging**
