### PR TITLE
fix: add message if type/paste function is called with an invalid element

### PR DESCRIPTION
**Pull request by marcosvega91**
**What**:

I have thrown a new `TypeError` if the user calls `userEvent.type` or `userEvent.paste` with an element that has no value. 
This PR is part of issue #356.

**Why**:

Because as it was before the PR the error was not very helpful

image

**How**:

By checking if the currentElement has value property. 
The message thrown is like this `the current element is of type BODY and doesn't have a valid value`

**Checklist**:

- [ ] Documentation
- [X] Tests
- [ ] Typings
- [X] Ready to be merged

### CODE REVIEW

**Comment by marcosvega91** [comment]
I'm looking the code better and maybe there could be other problems like this
https://github.com/testing-library/user-event/blob/50e330bc1d7249eea618405f8e3f70e32077ef07/src/type.js#L253-L254
https://github.com/testing-library/user-event/blob/50e330bc1d7249eea618405f8e3f70e32077ef07/src/type.js#L286-L287

Maybe we should use `currentValue` also in the other parts?

**Comment by kentcdodds** [comment]
Whatever you think makes the most sense 👍

**Comment by marcosvega91** [comment]
I have made the changes. I have updated also paste function with this logic

**Comment by kentcdodds** [comment]
@all-contributors please add @marcosvega91 for code and tests

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by marcosvega91** [comment]
thank you @kentcdodds, it's awesome. I'm really happy to be part of another team of testing library 🥳 .
I like a lot the project and I hope to do always good thing 🦇 

Thank you for all the things that you are doing for the community and the opportunity that you give to all of us ❤️

**Pull request merged**
