### PR TITLE
fix: 🐛 don't type on disabled or readonly inputs

### LINKED ISSUE #152: When typing in a disabled input onChange is still called
Test:
```js
import React from 'react'
import { render } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

    it('should not call onChange function when typing in a disabled field', () => {
        const onChange = jest.fn()
        const { getByPlaceholderText } = render(
            <input
                disabled
                id="test-id"
                name="test-name"
                onChange={onChange}
                placeholder="placeholder"
            />
        )
        userEvent.type(getByPlaceholderText('placeholder'), 'foo')
        expect(onChange).not.toHaveBeenCalled()
    })
```
I expect this test to succeed but it isn't.

Output:
```
    Expected mock function not to be called but it was called with:
      [{"_dispatchInstances": null, "_dispatchListeners": null, "_targetInst": null, "bubbles": null, "cancelable": null, "currentTarget": [Function currentTarget], "defaultPrevented": null, "dispatchConfig": null, "eventPhase": null, "isDefaultPrevented": [Function functionThatReturnsFalse], "isPropagationStopped": [Function functionThatReturnsFalse], "isTrusted": null, "nativeEvent": null, "target": null, "timeStamp": [Function timeStamp], "type": null}], [{"_dispatchInstances": null, "_dispatchListeners": null, "_targetInst": null, "bubbles": null, "cancelable": null, "currentTarget": [Function currentTarget], "defaultPrevented": null, "dispatchConfig": null, "eventPhase": null, "isDefaultPrevented": [Function functionThatReturnsFalse], "isPropagationStopped": [Function functionThatReturnsFalse], "isTrusted": null, "nativeEvent": null, "target": null, "timeStamp": [Function timeStamp], "type": null}], [{"_dispatchInstances": null, "_dispatchListeners": null, "_targetInst": null, "bubbles": null, "cancelable": null, "currentTarget": [Function currentTarget], "defaultPrevented": null, "dispatchConfig": null, "eventPhase": null, "isDefaultPrevented": [Function functionThatReturnsFalse], "isPropagationStopped": [Function functionThatReturnsFalse], "isTrusted": null, "nativeEvent": null, "target": null, "timeStamp": [Function timeStamp], "type": null}]
```

### PR DESCRIPTION
**Pull request by Gpx**
Closes #152

BREAKING CHANGE: disabled or readonly inputs won't be typeable anymore

### CODE REVIEW

**Comment by Gpx** [comment]
@afontcu I would appreciate if you could take a look at the Vue tests. I don't get what's wrong there 🙇

**Comment by afontcu** [comment]
> @afontcu I would appreciate if you could take a look at the Vue tests. I don't get what's wrong there 🙇

Hi! 👋  Just pushed a fix –  the "on" clause on events was the issue. I guess you'll need to rebase, but I wanted to let you see the diff :) Feel free to ping me if you want me to do that!

Cheers!

**Comment by Gpx** [comment]
Thank you @afontcu 🎉

**Pull request merged**
