### PR TITLE
fix tab focus on disabled elements false positive

### PR DESCRIPTION
**Pull request by kandros**
this PR fixes a false positive that allowed the `tab` function to focus disabled elements, which is not the browser behavior

done @ [Open Source Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/) Milano

### CODE REVIEW

**Comment by benmonro** [comment]
@kandros apologies, i just saw this now, thank you for adding this!

**Comment by benmonro** [comment]
@kentcdodds if this looks good to you can you merge plz?

**Comment by kentcdodds** [comment]
@all-contributors please add @kandros for code and tests

**Pull request merged**
