### PR TITLE
Reduce size of npm package by 99%

### PR DESCRIPTION
**Pull request by Raynos**
There exists a 12MB binary in the tarball published to npm called `cc-test-reporter`.

This looks like a happy accident to me. It's only neccessary on the CI machine and should be removed before publishing the library.

The npm tarball for `user-event` is 12.9MB ; of which 12.8MB is this `cc-test-reporter` binary.

### CODE REVIEW

**Comment by Raynos** [comment]
Travis failed because of 429 rate limiting on github when trying to git clone the source code.

**Comment by kentcdodds** [comment]
Thanks for this! I think this repo is due for some tooling improvements which I plan to make soon, but I'll get this merged now to fix this issue right now.

**Comment by Raynos** [comment]
Npm says the tarball is now 112kb and not 12.9mb

Thanks !

**Comment by kentcdodds** [comment]
Hooray! 🎉

**Pull request merged**
