### PR TITLE
Fix incorrect default import from @testing-library/dom

### PR DESCRIPTION
**Pull request by bryanjtc**
**What**:

Fixes: #1160 

**Why**:
`@testing-library/dom` doesn’t have a default export.

When trying to import and resolve a default export from `@testing-library/dom` the package would fail.

**How**:

Removing the default export
**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Looks good! Thanks!

**Comment by bryanjtc** [comment]
Just to make sure, I will replace any other default export from `@testing-library/dom`. Since the change I made only fixes one.

**Comment by yannbf** [comment]
@kentcdodds would you mind checking this whenever you have time? thanks!

**Comment by kentcdodds** [comment]
Thanks for the ping @yannbf!

**Comment by kentcdodds** [comment]
Thanks for the contribution @bryanjtc!

**Comment by berekuk** [comment]
Thanks for this!
Somehow it still doesn't work for me for default imports in Typescript:

Captura de pantalla 2023-09-15 a la(s) 12 30 46

But named import now is fine (I think it wasn't before, with my Typescript setup).

**Pull request merged**
