### PR TITLE
feat: add userEvent.clear

### PR DESCRIPTION
**Pull request by wachunga**
This is a useful thing that Cypress provides. I've seen it requested a [few](https://github.com/testing-library/user-event/issues/232) [times](https://github.com/testing-library/user-event/issues/226) and recently missed it myself. 

This approach closely resembles how Cypress implements it: [{selectall}{backspace}](https://docs.cypress.io/api/commands/clear.html#Syntax). Because we don't have support for special keys yet, I simulated the relevant events but used double click for select all.

If you'd like, I can update the docs too.

### CODE REVIEW

**Comment by wachunga** [comment]
I wrote this in a generic way to accommodate future support of a backspace key, but that's hurting the code coverage. (No way to test it because we don't expose that yet through userEvent.) Guess I'll simplify the backspace logic until we want `type` to support that.

**Comment by wachunga** [comment]
@Gpx When you have a moment, could you review? Thanks!

**Comment by Gpx** [comment]
Thank you 🙇

**Pull request merged**
