### PR TITLE
Support Home and End key events

### PR DESCRIPTION
**Pull request by bozdoz**
**What**:

Add support for Home and End keys to `userEvent.type`

**Why**:

Useful for accessibility tests for a Tabs component for example (home and end move focus to first and last elements): https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

**How**:

I modelled the changes after #511, adding two functions `handleHome` and `handleEnd`, two tests, and updated the README

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Typings
- [x] Ready to be merged

### CODE REVIEW

**Comment by vasilii-kovalev** [comment]
It is also necessary to adjust [specialChars](https://github.com/testing-library/user-event#specialchars) section and [appropriate types](https://github.com/testing-library/user-event/blob/d9b3e4ef0456b0277b63eecb0451f965915dcc44/typings/index.d.ts#L78-L90).
@bozdoz, could you do that, please?

**Review by nickmccurdy — APPROVED** [review]

**Comment by curiosity26** [comment]
I noticed this after creating #537. Sorry for the dupe. But I noticed this implementation doesn't encapsulate cursor positioning. FWIW I do handle cursor positioning with home and end in my PR

**Comment by ph-fritsche** [comment]
Closing this as resolved by #536

**Comment by nickmccurdy** [comment]
This PR has some nice changes like updating the character table in the readme that weren't in #536. I can open a PR with anything that's missing and credit @bozdoz soon.

**Comment by ph-fritsche** [comment]
Does [0d74a58](https://github.com/testing-library/user-event/commit/0d74a58b8ff87ecea0775b659b4c9b69e9ff9ca0) contain the missing changes?

**Comment by ph-fritsche** [comment]
@nickmccurdy @bozdoz Could you confirm so that I could push it to master or add missing parts to it?

**Pull request closed without merging**
