### PR TITLE
Fix leading number being trimmed on point type

### PR DESCRIPTION
**Pull request by lourenci**
**What**:

It solves #360.

**How**:

In the actual code handling the point, I concatenate the input's previous value.
I tried to keep the changes as little as possible once I'm not used to neither to the events nor to the lib.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] Typings
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
@all-contributors please add @lourenci for code and tests

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by lourenci** [comment]
> Thanks so much for your help! I've added you as a collaborator on the project.

Thank you so much for this. I'll try to help the community as much as I can. 

My next step is to become a member of the @testing-library org. 😊

**Pull request merged**
