### PR TITLE
Implement arrow interactions as arrowPress

### PR DESCRIPTION
**Pull request by juanca**
**What**: Add arrow interactions to the user-event API

**Why**: Arrow interactions emit key down event, maybe a key press event (I need help on this), and a key up event -- in that particular order. Arrow interactions are crucial in implementing accessibility support for UI widgets. However, there are more than just arrows -- we also need a HOME and END (to name a couple) keys support.  

**How**: Adds an `arrowPress` function to the module API -- however, perhaps it makes more sense to expose these interactions as a different API (and for better long-term purposes)

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] Typings
- [ ] Ready to be merged
      

This is not ready to be merged. As I developed this, I figured I should get more feedback on the API design and testing design. I can follow up on documentation and typing -- though, I will be honest, I don't know how typing are defined in this repository -- and any additional PR checklist/revisions/what-have-yous. 

Thank you for your time!

### CODE REVIEW

**Comment by juanca** [comment]
Uh, looks like my IDE removed a bunch of things. 🤔 I didn't see those changes in `git add --patch`

**Comment by nickmccurdy** [comment]
This seems similar to #354, what do you think about it? I started writing tests but you can help out with the implementation if you'd like.

**Comment by juanca** [comment]
I'm open to collaborating. Let me know the repo#branch combo and I can start digging later today / tomorrow as I balance some work priorities with downtime.

**Comment by nickmccurdy** [comment]
Sorry I got distracted and my test doesn't really have any useful assertions (just a snapshot that's currently incorrect), but here's what I started with as an example:

```js
test('{right} on a radio button', () => {
  const {element: button, getEventCalls} = setup(
    <>
      <input type="radio" name="example" defaultChecked />
      <input type="radio" name="example" />
      <input type="radio" name="example" />
    </>,
  )

  userEvent.type(button, '{right}')
})
```

After this only the second radio should be checked.

**Comment by juanca** [comment]
I ended up going a different route: using the event snapshot. See https://github.com/testing-library/user-event/pull/371

Feedback on the PR would be appreciated. Let me know if this is aligned with your thoughts on the user-event API -- I may have done one too many assumptions.

**Pull request closed without merging**
